baseURL = "https://juniorjb5.github.io/ANIF/"
languageCode = "en-us"
title = " "
theme = "hugo-arcana-main"
copyright = "© All rights reserved"

defaultContentLanguage = "es"


[taxonomies]
    tag = "tags"

[params]
    description = "Analítica e Ingeniería Financiera"
    images = ['https://juniorjb5.github.io/ANIF/images/favicon.png']
    show_post_dates = false
    favicon = ["/images/favicon.png"]

    
    [[params.social]]
        title = "GitHub"
        icon = "fa-github"
        url = "#"
    [[params.social]]
        title = "LinkedIn"
        icon = "fa-linkedin-in"
        url = "https://www.linkedin.com/in/semillero-de-investigaci%C3%B3n-anif-48b71b356/"
    



    [params.footer]

        [[params.footer.links]]
            header = ""
        [[params.footer.links.links]]
            title = "Universidad del Valle"
            url = "https://www.univalle.edu.co/"
        [[params.footer.links.links]]
            title = "Facultad de Ingeniería"
            url = "https://ingenieria.univalle.edu.co/"
        [[params.footer.links.links]]
            title = "Escuela de Ingeniería Industrial"
            url = "https://industrial.univalle.edu.co/"

        
        
        [[params.footer.links]]
            header = ""
        [[params.footer.links.links]]
            title = "GrupLAC"
            url = "https://scienti.minciencias.gov.co/gruplac/jsp/visualiza/visualizagr.jsp?nro=00000000013799"
        [[params.footer.links.links]]
            title = "Director "
            url = "https://industrial.univalle.edu.co/profesores/diego-fernando-manotas-duque"
      
        [params.footer.contact_form]
            enabled = true
            header = "Contáctanos"
            action = ""


  

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


